console.log('\t\t\t\t*\t\t\t\t\t\t\t\t\t\t\t*\t\t\t\t\t\t\t\t*');
console.log('\t\t\t\t\t\t\t*\t\t\t\t\t\t\t\t\t\t\t*');
console.log('\t*\t\t\t\t\t\t\t\t\t*\t\t\t\t*\t\t\t\t\t\t*\t\t\t\t\t*');
console.log('\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t __(_)__');
console.log('\t\t\t\t*\t\t\t\t\t\t\t\t*\t\t\t\t\t\t\t\t\t\t(_*___*_)');
console.log('\t\t*\t  ===  =====   ===   ====\t\t==\t\t*\t   ==  ===\t ====\t ===\t\t  |\t  |');
console.log('*\t\t\t =\t\t =\t  =\t  =\t =\t =\t\t  =\t\t\t  =\t  =\t  =\t =\t =\t=');
console.log('\t\t\t  ===\t =\t  = = =\t ====\t *\t   =\t=\t =\t  = = =\t ====\t ===');
console.log('\t  *\t\t\t =\t =\t  =\t  =\t =\t =\t\t\t=  = =\t=  *  =\t  =  =\t =\t\t=\t*');
console.log('\t*\t\t  ===\t =\t  = ` =\t =\t  =\t\t\t ==\t  ==\t  =\t  =\t =\t  =\t ===');
console.log('\t\t\t\t\t\t\t`\t*\t\t\t\t\t\t\t\t  *\t\t\t\t\t*\t\t\t\t\t\t\t*');
console.log('\t\t\t*\t\t\t\t`\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t*');
console.log('\t\t\t\t\t\t\t`');
console.log('\t\t*\t\t\t\t\t\t\t\t\t*\t\t\t\t\t\t\t\t\t\t\t\t\t\t*');
console.log('\t\t\t\t\t\t\t|\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t `');
console.log('\t*\t\t\t\t   *   [_]\t\t\t\t\t\t\t\t*\t\t\t\t\t\t  *\t `\t\t\t\t\t\t\t\t\t*');
console.log('\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t `');
console.log('\t\t\t*\t\t\t\t\t\t*\t\t\t\t\t\t\t\t\t*\t\t\t\t\t\t\t\t\t\t*');
console.log('\t  *\t\t\t\t*');
console.log('\t\t\t\t\t\t\t\t\t\t  __( )__\t\t\t\t\t\t\t\t\t\t |');
console.log('\t\t\t\t*\t\t\t\t\t\t (_*___*_)\t\t\t\t*\t\t\t\t\t\t[_]\t\t\t\t\t\t\t\t*');
console.log('\t\t\t\t\t\t\t\t\t\t   |   |');
